import os
import fnmatch

# --- Настройки ---
OUTPUT_FILE = "SUMMARY.txt"
SCRIPT_NAME = os.path.basename(__file__)

# Стандартные исключения
DEFAULT_IGNORES = [
    ".git",
    "__pycache__",
    ".idea",
    ".vscode",
    "venv",
    ".venv",
    "env",
    "*.pyc",
    "*.png", "*.jpg", "*.jpeg", "*.gif", "*.ico", "*.svg", # Бинарные медиа
    "*.db", "*.sqlite", "*.sqlite3", # Базы данных
    "poetry.lock",
    OUTPUT_FILE,
    SCRIPT_NAME
]

def read_gitignore(root_path):
    """Считывает паттерны из .gitignore и добавляет стандартные."""
    patterns = []
    gitignore_path = os.path.join(root_path, ".gitignore")
    
    patterns.extend(DEFAULT_IGNORES)

    if os.path.exists(gitignore_path):
        try:
            with open(gitignore_path, "r", encoding="utf-8") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#"):
                        patterns.append(line)
        except Exception as e:
            print(f"Ошибка чтения .gitignore: {e}")
            
    return patterns

def is_ignored(path, patterns, root_path):
    """Проверяет, попадает ли путь под паттерны игнорирования."""
    rel_path = os.path.relpath(path, root_path)
    if rel_path == ".":
        return False
        
    filename = os.path.basename(path)
    
    for pattern in patterns:
        clean_pattern = pattern.rstrip("/")
        
        # 1. По имени файла
        if fnmatch.fnmatch(filename, clean_pattern):
            return True
        # 2. По относительному пути
        if fnmatch.fnmatch(rel_path, clean_pattern):
            return True
        # 3. По пути директории
        if pattern.endswith("/") or os.path.isdir(os.path.join(root_path, pattern)):
             parts = rel_path.split(os.sep)
             if clean_pattern in parts:
                 return True

    return False

def generate_tree(dir_path, patterns, root_path, prefix=""):
    """Рекурсивно генерирует строку с деревом каталогов."""
    tree_str = ""
    
    try:
        items = os.listdir(dir_path)
        items.sort(key=lambda x: (not os.path.isdir(os.path.join(dir_path, x)), x.lower()))
    except PermissionError:
        return ""

    filtered_items = []
    for item in items:
        full_path = os.path.join(dir_path, item)
        if not is_ignored(full_path, patterns, root_path):
            filtered_items.append(item)

    for index, item in enumerate(filtered_items):
        full_path = os.path.join(dir_path, item)
        is_last = (index == len(filtered_items) - 1)
        
        connector = "└── " if is_last else "├── "
        tree_str += f"{prefix}{connector}{item}\n"
        
        if os.path.isdir(full_path):
            extension = "    " if is_last else "│   "
            tree_str += generate_tree(full_path, patterns, root_path, prefix + extension)
            
    return tree_str

def main():
    root_dir = os.getcwd()
    patterns = read_gitignore(root_dir)
    
    print(f"Сборка проекта в {OUTPUT_FILE}...")
    
    with open(OUTPUT_FILE, "w", encoding="utf-8") as outfile:
        # 1. Записываем заголовок и дерево
        outfile.write("# PROJECT SUMMARY\n")
        outfile.write(f"# Generated by {SCRIPT_NAME}\n\n")
        
        outfile.write("## PROJECT STRUCTURE\n")
        outfile.write("```text\n")
        outfile.write(".\n")
        tree_content = generate_tree(root_dir, patterns, root_dir)
        outfile.write(tree_content)
        outfile.write("```\n\n")
        
        outfile.write("## FILE CONTENTS\n\n")

        # 2. Обходим файлы
        file_count = 0
        for dirpath, dirnames, filenames in os.walk(root_dir):
            # Фильтрация папок
            for dirname in list(dirnames):
                full_dir_path = os.path.join(dirpath, dirname)
                if is_ignored(full_dir_path, patterns, root_dir):
                    dirnames.remove(dirname)

            for filename in filenames:
                file_path = os.path.join(dirpath, filename)
                
                if is_ignored(file_path, patterns, root_dir):
                    continue
                
                rel_path = os.path.relpath(file_path, root_dir).replace(os.sep, '/')
                header = f"./{rel_path}"
                
                try:
                    with open(file_path, "r", encoding="utf-8") as infile:
                        content = infile.read()
                        
                    # Начало файла
                    outfile.write(f"### {header} ###\n")
                    outfile.write(content)
                    
                    # Гарантируем перенос строки, если файл заканчивается кодом без \n
                    if content and not content.endswith("\n"):
                        outfile.write("\n")
                    
                    # Конец файла (примечание для LLM)
                    outfile.write(f"# --- End of {header} ---\n\n")
                    
                    file_count += 1
                    
                except UnicodeDecodeError:
                    pass
                except Exception as e:
                    print(f"Ошибка чтения {header}: {e}")

    print(f"Готово! Обработано файлов: {file_count}. Результат в {OUTPUT_FILE}")

if __name__ == "__main__":
    main()